PRODUCT_VERSION_MAJOR = 16
PRODUCT_VERSION_MINOR = 0

ifeq ($(FUNDAMENTAL_VERSION_APPEND_TIME_OF_DAY),true)
    FUNDAMENTAL_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    FUNDAMENTAL_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set FUNDAMENTAL_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef FUNDAMENTAL_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "LINEAGE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^LINEAGE_||g')
        FUNDAMENTAL_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(FUNDAMENTAL_BUILDTYPE)),)
    FUNDAMENTAL_BUILDTYPE := UNOFFICIAL
    FUNDAMENTAL_EXTRAVERSION :=
endif

ifeq ($(FUNDAMENTAL_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        FUNDAMENTAL_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

FUNDAMENTAL_VERSION_SUFFIX := $(FUNDAMENTAL_BUILD_DATE)-$(FUNDAMENTAL_BUILDTYPE)$(FUNDAMENTAL_EXTRAVERSION)-$(FUNDAMENTAL_BUILD)

# Internal version
FUNDAMENTAL_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(FUNDAMENTAL_VERSION_SUFFIX)

# Display version
FUNDAMENTAL_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(FUNDAMENTAL_VERSION_SUFFIX)

# LineageOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.lineage.version=$(FUNDAMENTAL_VERSION) \
    ro.lineage.display.version=$(FUNDAMENTAL_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(FUNDAMENTAL_BUILDTYPE)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.fundamental.version=$(FUNDAMENTAL_VERSION) \
    ro.fundamental.display.version=$(FUNDAMENTAL_DISPLAY_VERSION) \
    ro.fundamental.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.fundamental.releasetype=$(FUNDAMENTAL_BUILDTYPE)
